/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/lH5raPRpvt3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export interface Job {
  id: number;
  title: string;
  company: string;
  location: string;
  description: string;
}

interface ComponentProps {
  jobs: Job[];
}

export function Component({ jobs }: ComponentProps) {
  return (
    <section className="bg-background py-12 md:py-16 lg:py-20">
      <div className="container px-4 md:px-6">
        <h1 className="mb-8 text-3xl font-bold tracking-tight md:text-4xl">Job Listings</h1>
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {jobs.map((job) => (
            <div key={job.id} className="rounded-lg bg-card p-6 shadow-sm transition-all duration-300 hover:shadow-lg">
              <h2 className="mb-2 text-xl font-semibold">{job.title}</h2>
              <div className="mb-4 text-muted-foreground">
                {job.company} - {job.location}
              </div>
              <p className="text-sm text-muted-foreground">{job.description}</p>
              <div className="mt-4">
                <Button size="sm">Apply Now</Button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
